package com.programming_II_CSC202.Activities.Activity_1;
// Coded with respect to the UML design for Student class
public class Student {
    private int id;
    private String name;
    private static float gpa;
    private long phone = 556170992L;
    private int year;

    void Student(){
        // This is the default constructor
        // Optional because it's auto generated by the JVM
    }

    public int id(int id) {
        return this.id = id;
    }

    public int setId(int id) {
        return this.id = id;
    }

    public static float getGpa() {
        return gpa;
    }

    public String setName(String name) { //forgot to add parameter for setting name in the uml
        return this.name = name;
    }

    public long getPhone() {
        return phone;
    }

    public int setYear(int year) {
        return this.year = year;
    }

    public String generateStatus() {
        return "online";
    }
}
